name: Workflow Java

on: [push] # Déclenche le workflow lors d'un push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Configurer Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Installer Apache Maven
      run: sudo apt-get install -y maven

    - name: Compilation et Tests
      run: mvn clean install -B
  
    - name: Exécution du programme
      run: java src/main/java Main



